name: Webhook

on: 
  push: 
    branches: ["master"]
  pull_request: 
    branches: ["master"]
  
jobs: 
  Webhook: 
    runs-on: ubuntu-latest
    steps:
    - name: Invoke deployment hook
      uses: distributhor/workflow-webhook@v3
      if: ${{contains(github.event.head_commit.message, '#update')}}
      env:
        webhook_url: ${{ secrets.WEBHOOK_URL }}
        webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
        data: '{"nombre": "Alejandro"}'
